### PR TITLE
Creating test user service; Add fraud prevention headers

### PR DESCRIPTION
**Pull request by DarkSide666**
**Features:**
* Adds service for creating test users
* Adds fraud prevention headers
* Adds ability to set default headers for all requests (trough Request object or Environment)
* Adds connection method header values

**Fixes:**
* OAuth should use RequestURL constants too

**Usage example:**
```
use HMRC\Environment\Environment;
use HMRC\Request\RequestHeader;
use HMRC\Request\RequestHeaderValue;

Environment::getInstance()->setDefaultRequestHeaders([
    RequestHeader::GOV_CLIENT_CONNECTION_METHOD => RequestHeaderValue::WEB_APP_VIA_SERVER,
    RequestHeader::GOV_CLIENT_PUBLIC_IP => $_SERVER['REMOTE_ADDR'],
    RequestHeader::GOV_CLIENT_PUBLIC_PORT => $_SERVER['REMOTE_PORT'],
    RequestHeader::GOV_CLIENT_USER_AGENT => $_SERVER['HTTP_USER_AGENT'],
    RequestHeader::GOV_CLIENT_USER_IDS => 'user='.$this->user->id,
    RequestHeader::GOV_VENDOR_VERSION => 'app='.$this->app->version,
]);
```

### CODE REVIEW

**Comment by s-patompong** [comment]
Sorry I was busy and just see this today. I'll need to have a look at the code and will merge if everything is ok.

**Comment by DarkSide666** [comment]
No problem. I will use this PR in production after release which will happen this Sunday, so it has to be OK.
Also guy from HMRC few days ago took a look at our test server and approved that all works nicely with them.

**Comment by s-patompong** [comment]
I did change $request_headers to $requestHeaders in Environment class. This is for consistency of the project. I'll find a way to add the rule into StypeCI.

**Comment by s-patompong** [comment]
PR is merged to master and released as v1.2.0 (https://github.com/s-patompong/hmrc-api-php/releases/tag/v1.2.0)

**Pull request merged**
